# set_map.py
# Extremely high-certainty matches only.

SET_MAP = {
    "pokemon-ancient-origins": "Ancient Origins Set",
    "pokemon-arceus": "Platinum - Arceus Set",
    "pokemon-aquapolis": "Aquapolis Set",
    "pokemon-astral-radiance": "Astral Radiance Set",
    "pokemon-base-set": "Base Set Set",
    "pokemon-base-set-2": "Base Set 2 Set",
    "pokemon-battle-styles": "Battle Styles Set",
    "pokemon-best-of-game": "Best of Game Set",
    "pokemon-black-&-white": "Black & White Set",
    "pokemon-black-bolt": "Black Bolt Set",
    "pokemon-boundaries-crossed": "Boundaries Crossed Set",
    "pokemon-breakthrough": "XY BREAKthrough Set",
    "pokemon-breakpoint": "BREAKPoint Set",
    "pokemon-brilliant-stars": "Brilliant Stars Set",
    "pokemon-burning-shadows": "Burning Shadows Set",
    "pokemon-call-of-legends": "Call of Legends Set",
    "pokemon-celebrations": "Celebrations Set",
    "pokemon-celestial-storm": "Celestial Storm Set",
    "pokemon-champion%27s-path": "Champion's Path Set",
    "pokemon-chilling-reign": "Chilling Reign Set",
    "pokemon-cosmic-eclipse": "Cosmic Eclipse Set",
    "pokemon-crimson-invasion": "Crimson Invasion Set",
    "pokemon-crown-zenith": "Crown Zenith Set",
    "pokemon-crystal-guardians": "EX Crystal Guardians Set",
    "pokemon-dark-explorers": "Dark Explorers Set",
    "pokemon-darkness-ablaze": "Darkness Ablaze Set",
    "pokemon-deoxys": "EX Deoxys Set",
    "pokemon-delta-species":"EX Delta Species Set",
    "pokemon-destined-rivals": "Destined Rivals Set",
    "pokemon-detective-pikachu": "Detective Pikachu Set",
    "pokemon-diamond-&-pearl": "Diamond & Pearl Set",
    "pokemon-double-crisis": "Double Crisis Set",
    "pokemon-dragon": "EX Dragon Set",
    "pokemon-dragon-frontiers": "EX Dragon Frontiers Set",
    "pokemon-dragon-majesty": "Dragon Majesty Set",
    "pokemon-dragon-vault": "Dragon Vault Set",
    "pokemon-dragons-exalted": "Dragons Exalted Set",
    "pokemon-emerging-powers": "Emerging Powers Set",
    "pokmeon-emerald": "EX Emerald Set",
    "pokemon-evolutions": "Evolutions Set",
    "pokemon-evolving-skies": "Evolving Skies Set",
    "pokemon-expedition": "Expedition Set",
    "pokemon-fates-collide": "Fates Collide Set",
    "pokemon-fire-red-&-leaf-green": "EX FireRed & LeafGreen Set",
    "pokemon-flashfire": "XY Flashfire Set",
    "pokemon-forbidden-light": "Forbidden Light Set",
    "pokemon-fossil": "Fossil Set",
    "pokemon-furious-fists": "Furious Fists Set",
    "pokemon-fusion-strike": "Fusion Strike Set",
    "pokemon-generations": "Generations Set",
    "pokemon-go": "Pokemon Go Set",
    "pokemon-great-encounters": "Great Encounters Set",
    "pokemon-guardians-rising": "Guardians Rising Set",
    "pokemon-gym-challenge": "Gym Challenge Set",
    "pokemon-gym-heroes": "Gym Heroes Set",
    "pokemon-heartgold-&-soulsilver": "HeartGold SoulSilver Set",
    "pokemon-hidden-fates": "Hidden Fates Set",
    "pokemon-hidden-legends":"EX Hidden Legends Set",
    "pokemon-holon-phantoms": "EX Holon Phantoms Set",
    # Intentionally NOT mapped: Pokellector lists Journey Together base_total=180
    # (counts secret rares), but cards print /159. Mapping it lets backfill_set_meta
    # overwrite the corrected base_total (159, set via update_journey_together.py)
    # back to 180, which breaks matching for /159 cards. Leave unmapped.
    # "pokemon-journey-together": "Journey Together Set",
    "pokemon-jungle": "Jungle Set",
    "pokemon-legendary-collection": "Legendary Collection Set",
    "pokemon-legendary-treasures": "Legendary Treasures Set",
    "pokemon-legend-maker": "EX Legend Maker Set",
    "pokemon-legends-awakened": "Legends Awakened Set",
    "pokemon-lost-origin": "Lost Origin Set",
    "pokemon-lost-thunder": "Lost Thunder Set",
    "pokemon-majestic-dawn": "Majestic Dawn Set",
    "pokemon-mega-evolution": "Mega Evolution Set",
    "pokemon-mysterious-treasures": "Mysterious Treasures Set",
    "pokemon-neo-destiny": "Neo Destiny Set",
    "pokemon-neo-discovery": "Neo Discovery Set",
    "pokemon-neo-genesis": "Neo Genesis Set",
    "pokemon-neo-revelation": "Neo Revelation Set",
    "pokemon-next-destinies": "Next Destinies Set",
    "pokemon-noble-victories": "Noble Victories Set",
    "pokemon-obsidian-flames": "Obsidian Flames Set",
    "pokemon-paldea-evolved": "Paldea Evolved Set",
    "pokemon-paradox-rift": "Paradox Rift Set",
    "pokemon-phantasmal-flames": "Phantasmal Flames Set",
    "pokemon-phantom-forces": "Phantom Forces Set",
    "pokemon-plasma-blast": "Plasma Blast Set",
    "pokemon-plasma-freeze": "Plasma Freeze Set",
    "pokemon-plasma-storm": "Plasma Storm Set",
    "pokemon-platinum": "Platinum Set",
    "pokemon-power-keepers": "EX Power Keepers Set",
    "pokemon-primal-clash": "Primal Clash Set",
    "pokemon-prismatic-evolutions": "Prismatic Evolutions Set",
    "pokemon-rebel-clash": "Rebel Clash Set",
    "pokemon-roaring-skies": "Roaring Skies Set",
    "pokemon-ruby-&-sapphire": "EX Ruby & Sapphire",
    "pokemon-sandstorm": "EX Sandstorm",
    "pokemon-scarlet-&-violet": "Scarlet & Violet Set",
    "pokemon-scarlet-&-violet-151": "Scarlet & Violet - 151 Set",
    "pokemon-secret-wonders": "Secret Wonders Set",
    "pokemon-shining-fates": "Shining Fates Set",
    "pokemon-shining-legends": "Shining Legends Set",
    "pokemon-shrouded-fable": "Shrouded Fable Set",
    "pokemon-silver-tempest": "Silver Tempest Set",
    "pokemon-skyridge": "Skyridge Set",
    "pokemon-southern-islands": "Southern Islands Set",
    "pokemon-steam-siege": "Steam Siege Set",
    "pokemon-stellar-crown": "Stellar Crown Set",
    "pokemon-stormfront": "Stormfront Set",
    "pokemon-sun-&-moon": "Sun & Moon Set",
    "pokemon-surging-sparks": "Surging Sparks Set",
    "pokemon-supreme-victors": "Platinum - Supreme Victors Set",
    "pokemon-sword-&-shield": "Sword & Shield Set",
    "pokemon-team-magma-&-team-aqua": "EX Team Magma vs Team Aqua Set",
    "pokemon-team-rocket": "Team Rocket Set",
    "pokemon-team-rocket-returns": "EX Team Rocket Returns Set",
    "pokemon-team-up": "Team Up Set",
    "pokemon-temporal-forces": "Temporal Forces Set",
    "pokemon-twilight-masquerade": "Twilight Masquerade Set",
    "pokemon-ultra-prism": "Ultra Prism Set",
    "pokemon-unbroken-bonds": "Unbroken Bonds Set",
    "pokemon-unseen-forces": "EX Unseen Forces Set",
    "pokemon-unified-minds": "Unified Minds Set",
    "pokemon-unleashed": "HS Unleashed Set",
    "pokemon-vivid-voltage": "Vivid Voltage Set",
    "pokemon-white-flare": "White Flare Set",
    "pokemon-xy": "XY Set"
}

